### ISSUE TITLE
Ability to configure each output from let's say a web interface or some DIP switches (using binary for selecting the universe)

### ISSUE THREAD

**Issue by nt2ds** [CShark/usb_dmx#5]
I want to build this node but configuring each port through resistors and changing them day to day isn't the easiest thing.
Are the plans of adding a web interface to configure each port or adding DIP switches on the PCB to choose every port receives from which chip (MAX3440E)?

**Comment by CShark** [comment]
Currently you can reconfigure the Input / Output using the supplied software and the resistors are only for the initial configuration after a hard reset.

Regarding Dip-Switches: In the future there might be a PCB reiteration to add USB-C instead of the USB-B connector, I'll see if I can replace the resistors with dip-switches then.

Regarding WebUI: Currently the memory is a _bit_ (very) tight, so I'm probably unable to add a webUI without a PCB-Revision. Will look into taking that into account if I do one though.

Regarding Remapping: Not sure why you'd want to do that? I mean, you can just redefine the ArtNET Universe to either send to a different port or let the port receive a different Universe, so it is already remappable through software.

**Comment by CShark** [comment]
PCB revision is done, WebUI is also done (66b1ba0). Has now dip-switches for the config reset state and a WebUI for reconfiguration instead of that janky tool.
