### ISSUE TITLE
Empty submodule folder & Ethernet Jack

### ISSUE THREAD

**Issue by AlexSmith2025** [CShark/usb_dmx#7]
I want to repeat your project. where can i get the missing file folders?   lwip     And is it possible to make not a USB but an Internet connector.  thanks my mail smith.show2025@gmail.com

**Comment by CShark** [comment]
Hey, lwip is a submodule from another repo, you'll have to initialize it using `git submodule update --init --recursive`

As for Ethernet, it is currently out of scope for my personal needs.  You'd have to remove a port on the front to make room for an ethernet port and add a separate MAC/PHY, because the STM32G4 series does not have MII support. If you want to support PoE in addition you'll also have to add the specific magnetics, PoE negotiation chips and a power fallback circuit.

It does sound like a nice challenge though. Maybe I'll revisit it in a couple of years.
